apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "testapp.fullname" . }}-app
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ include "testapp.fullname" . }}-app
  template:
    metadata:
      labels:
        app: {{ include "testapp.fullname" . }}-app
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.app.port }}
          command:
            - sh
            - -c
            - |
              python manage.py migrate &&
              python manage.py runserver 0.0.0.0:{{ .Values.app.port }}
          env:
            - name: DB_HOST
              value: {{ include "testapp.fullname" . }}-db
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: {{ include "testapp.fullname" . }}-db
                  key: DB_NAME
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "testapp.fullname" . }}-db
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ include "testapp.fullname" . }}-db
                  key: DB_PASS
