apiVersion: v1
kind: Secret
metadata:
  name: {{ include "testapp.fullname" . }}-db
type: Opaque
stringData:
  DB_NAME: {{ .Values.postgres.db | quote }}
  DB_USER: {{ .Values.postgres.user | quote }}
  DB_PASS: {{ .Values.postgres.password | quote }}
